=== AnantLabs/codesmith/Templates/Frameworks/APOSA/ProceduresToMap.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Project">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="NameSpace" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="RecordSets" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="RecordSet" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="UpdateStoredProcedure" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Command" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Owner" type="xs:string" />
                                <xs:element name="Name" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="ExcludedFromRules" minOccurs="0" maxOccurs="1" type="xs:string">
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="SelectStoredProcedure" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Command" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Owner" type="xs:string" />
                                <xs:element name="Name" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="ExcludedFromRules" minOccurs="0" maxOccurs="1" type="xs:string">
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="SelectCollectionStoredProcedure" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Command" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Owner" type="xs:string" />
                                <xs:element name="Name" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="ExcludedFromRules" minOccurs="0" maxOccurs="1" type="xs:string">
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AnantLabs/codesmith/Templates/APOSA/ProceduresToMap.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ProceduresToMap.xsd">
  <NameSpace>Test</NameSpace>
  <RecordSets>
	  <RecordSet>
      <Name>User</Name>
      <UpdateStoredProcedure>
        <Command>
          <Owner>dbo</Owner>
          <Name>aposa_SetUserData</Name>          
        </Command>
        <ExcludedFromRules>UserID</ExcludedFromRules>
      </UpdateStoredProcedure>
      <SelectStoredProcedure>
        <Command>
          <Owner>dbo</Owner>
          <Name>aposa_GetUserData</Name>
        </Command>
        <ExcludedFromRules></ExcludedFromRules>
      </SelectStoredProcedure>
      <SelectCollectionStoredProcedure>
        <Command>
          <Owner>dbo</Owner>
          <Name>aposa_GetUsersData</Name>
        </Command>
        <ExcludedFromRules></ExcludedFromRules>
      </SelectCollectionStoredProcedure>
    </RecordSet>
    <RecordSet>
      <Name>Product</Name>
      <UpdateStoredProcedure>
        <Command>
          <Owner>dbo</Owner>
          <Name>aposa_SetProductData</Name>          
        </Command>
        <ExcludedFromRules>ProductID</ExcludedFromRules>
      </UpdateStoredProcedure>
      <SelectStoredProcedure>
        <Command>
          <Owner>dbo</Owner>
          <Name>aposa_GetProductData</Name>
        </Command>
        <ExcludedFromRules></ExcludedFromRules>
      </SelectStoredProcedure>
      <SelectCollectionStoredProcedure>
        <Command>
          <Owner>dbo</Owner>
          <Name>aposa_GetProductsData</Name>
        </Command>
        <ExcludedFromRules></ExcludedFromRules>
      </SelectCollectionStoredProcedure>
    </RecordSet>
  </RecordSets>
</Project>
